### ISSUE TITLE
`Unhandled method textDocument/codeAction (Method not Found)` on initial install

### ISSUE THREAD

**Issue by linozen** [merrickluo/lsp-tailwindcss#13]
Hi there,
thanks for your efforts. I followed the installation requirements on Doom Emacs and consistently get this error message: 

`Error from the Language Server: Unhandled method textDocument/codeAction (Method not Found)`

**Comment by nipuna-perera** [comment]
I had it workin gin doom emacs, but after the latest update to lsp I am getting this same error. Tailwind is not working anymore.

**Comment by seshaljain** [comment]
I'm facing the same problem, 
```
Company: An error occurred in auto-begin
Company: backend (:separate company-capf company-yasnippet) error "Unhandled method textDocument/completion" with args (candidates )
Company: An error occurred in auto-begin
Company: backend (:separate company-capf company-yasnippet) error "Unhandled method textDocument/completion" with args (candidates t)
```

**Comment by nipuna-perera** [comment]
Has anyone gotten this to work? I tried pinning to different versions but didn't work. The newer versions of the intellisense plugin seems to have broken how this works. I can't even get the lsp to be detected anything beyond v0.6.1. Latest is `v0.6.6` and the server is not even identified even though it installs. The above errors seem to be thrown by the `v0.6.1`

**Comment by Lenic** [comment]
same to me: vscode plugin version 0.6.1, and my configuration:

```
(use-package lsp-tailwindcss)
```

**Comment by aswinmohanme** [comment]
Any updates ?

**Comment by merrickluo** [comment]
Sorry for missing the notification, it seems the configuration response is changed after 0.6.0 release, somehow it worked when I bump the version, I'm looking into it, if you want to use it right now, try setting 
```lsp
(setq lsp-tailwindcss-server-version "0.5.10")
```
and reinstall the server.

**Comment by hamzashahid-blit** [comment]
I still have this issue. It is not yet fixed. I am using use-package without any options.

**Comment by merrickluo** [comment]
@hamzashahid-blit thanks for reporting in, did you try update `lsp-tailwindcss` and then reinstall the server with `lsp-install-server`? If so, please try `M-x lsp-tailwindcss-installed-server-version` and let me know which version of server you are using, thanks.

**Comment by pedz** [comment]
`M-x lsp-tailwindcss-installed-server-version` reports back `0.9.1`. 
`*Messages*` has:
```
LSP :: Connected to [tailwindcss:60040/starting /Users/pedz/Source/rails-7-passkey-demo].
LSP :: tailwindcss:60040 initialized successfully in folders: (/Users/pedz/Source/rails-7-passkey-demo)
LSP :: Error from the Language Server: Unhandled method textDocument/documentColor (Method not Found)
LSP :: Error from the Language Server: Unhandled method textDocument/codeAction (Method not Found)
LSP :: Error from the Language Server: Unhandled method textDocument/documentLink (Method not Found)
```
`*lsp-log*`  ends with:
```
[Global] Adding watch patterns: /Users/pedz/Source/rails-7-passkey-demo/config/tailwind.config.js, /Users/pedz/Source/rails-7-passkey-demo/config, /Users/pedz/Source/rails-7-passkey-demo, /Users/pedz/Source, /Users/pedz, /Users, /
[config/tailwind.config.js] Initializing...
[config/tailwind.config.js] Failed to load workspace modules.
[config/tailwind.config.js] Using bundled version of `tailwindcss`: v3.1.8
[config/tailwind.config.js] Using bundled version of `postcss`: v8.3.9
[config/tailwind.config.js] Building...
```
in green so I'm assuming it is happy.

I'm new to all this so I don't know how it is suppose to be working.  The emacs mode line has the `tailwindcss:60040` minor mode tag.  When the cursor is on top of a class name, the mini buffer shows the definition of the class.

What I am hoping for is for something to provide me with a list of possible similar classes -- an auto complete type feature.

**Comment by merrickluo** [comment]
Hi @pedz, I had a similar issue a couple of days ago, it seems to be a lsp-mode issue, but I didn't dig too far, I just updated lsp-mode to the latest version then it's gone, can you try it?

**Comment by pedz** [comment]
I updated lsp-mode.  The top comment in lsp-mode.el says `Version: 8.0.1`.  I still have the issue.

I'm using containers.  The Emacs and npm / node / tailwindcss-intellisense are executing on the laptop.  The Ruby / Rails executables are inside a Docker container.  The application's code (and the HTML and CSS code) are shared between the two.  So... if the Tailwindcss Intellisense code needs to run the tailwindcss executable, it isn't going to be able to but it appears as if the tailwindcss code is there just to update what is shipped to the browser.

I'm also having weird issues with the completions.  Very sporadically, it works -- a completion list pops up as it should.  But it is very rare.

Last... there are times when just moving the cursor forward in the buffer is very slow.
