### ISSUE TITLE
Integrating Headwind Class Sorting

### ISSUE THREAD

**Issue by aswinmohanme** [merrickluo/lsp-tailwindcss#17]
Great work on the plugin, really helped me with the switch to Emacs too. 

Is there any plans to integrate https://marketplace.visualstudio.com/items?itemName=heybourn.headwind with this. Really helps with keeping the html file clean.

**Comment by merrickluo** [comment]
yeah, I checked the code for headwind, it does not connect to an lsp server and just a vscode extension, if we want to integrate that we need to rewrite it in lisp. I also find that there is an eslint plugin for sorting the class names, maybe it can be used with lsp-eslint?

**Comment by merrickluo** [comment]
forget to link: https://www.npmjs.com/package/eslint-plugin-tailwindcss

**Comment by shackra** [comment]
there is a CLI alternative https://github.com/avencera/rustywind

**Comment by shackra** [comment]
why was this close?
