### ISSUE TITLE
Problem cloning the repository 

### ISSUE THREAD

**Issue by wojtekgalaj** [merrickluo/lsp-tailwindcss#20]
Hi,

First of all, thanks for building this. :) <3

Now, I haven't been able to see this working yet. I'm using Doom Emacs and have followed your instructions for packages.el end config.el.

When I try to update or sync doom to update the packages and get your plugin, I get the following error:

`> Cloning lsp-tailwindc (for lsp-tailwindcss)...
      x The package manager threw an error
      x Last 25 lines of straight's error log:
        master
        [Return code: 0]
        $ cd /Users/wojtek/.emacs.d/.local/straight/repos/emacsmirror-mirror/
        $ git merge-base --is-ancestor master origin/master
        [Return code: 0]
        $ cd /Users/wojtek/.emacs.d/.local/straight/repos/emacsmirror-mirror/
        $ git merge-base --is-ancestor origin/master master
        [Return code: 0]
        $ cd /Users/wojtek/.emacs.d/.local/straight/repos/emacsmirror-mirror/
        $ git rev-parse HEAD
        fc970dcdc47b809ed393c5e40baaf49a38f889a1
        [Return code: 0]
        $ cd /Users/wojtek/.emacs.d/.local/straight/repos/
        $ git clone --origin origin --no-checkout https\://github.com/merrickluo/lsp-tailwindc.git /Users/wojtek/.emacs.d/.local/straight/repos/lsp-tailwindc/ --depth 1 --single-branch --no-tags
        Cloning into '/Users/wojtek/.emacs.d/.local/straight/repos/lsp-tailwindc'...
        fatal: could not read Username for 'https://github.com': Device not configured
        [Return code: 128]`

It's very likely the problem is between the monitor and the chair here but if you could help me figure out how to solve this I would be eternally grateful :)

I see it's to do with github dropping support for password auth, I understand a token is needed now but I don't know if it's something I can do or if you'd need to add it to this repository.

Thanks a ton again.

**Comment by merrickluo** [comment]
This repo is public, it should not require password or token for cloning it. I notice that the logs shows it trying to clone `https\://github.com/merrickluo/lsp-tailwindc.git`, did you miss typed in the recipe block? It should be like this
```emacs-lisp
(package! lsp-tailwindcss :recipe (:host github :repo "merrickluo/lsp-tailwindcss"))
```
