### ISSUE TITLE
Use lsp-tailwindcss on different file types

### ISSUE THREAD

**Issue by fapapa** [merrickluo/lsp-tailwindcss#24]
Hi!

First of all, thank you for writing this package, it is so helpful to me!

I've been trying to figure out how to use it for other file types. For example, I use Rails, which has *.html.erb files, which are essentially html with some dynamic bits sprinkled in. It is a web-mode file, and when I run `M-x lsp` it prints out `Warning (lsp-mode): Unable to calculate the languageId for buffer ‘index.html.erb’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is web-mode` several times.

I'm kind of a newb when it comes to LSP (the only reason I'm using it at all is for this package!), so I'm really not sure how to solve this.

**Comment by merrickluo** [comment]
Yeah, that's because lsp-mode does not know which language `web-mode` should be associated to, you can specify it with the file suffix like
```emacs-lisp
(add-to-list 'lsp-language-id-configuration '(".*\\.erb$" . "html")
```
You can learn more about this by `M-x describe-variable lsp-language-id-configuration`
