### ISSUE TITLE
How to setup with elixir .heex file?

### ISSUE THREAD

**Issue by RobinBeekhof** [merrickluo/lsp-tailwindcss#26]
Hi,

I'm trying to configure lsp-tailwindcss for .heex files in Doom emacs. I have done the setup as you described and added to my config.el:

`(use-package! lsp-tailwindcss :init (setq! lsp-tailwindcss-add-on-mode t))`
`(add-to-list 'lsp-language-id-configuration '(".*\\.heex$" . "html"))
`

both html-ls and tailwind-ls seem to start fine
`LSP :: Connected to [html-ls:29522/starting][tailwindcss:29523/starting].
LSP :: tailwindcss:29523 initialized successfully in folders: (/****)
LSP :: html-ls:29522 initialized successfully in folders: (/****)
`

However, It is not really working. For example, when editing the .heex file, I'm not getting any tailwind suggestions.

![image](https://user-images.githubusercontent.com/50193227/139558283-53e4bcee-e225-4d36-bee8-525e785d2710.png)

I don't know what I'm doing wrong. I hope somebody can help :)

**Comment by merrickluo** [comment]
I'm not sure about heex, but it did work for me in leex files. The lsp log indicates that servers are starting, but might not start correctly, can you try 
- M-x lsp-describe-session // and find your current project to see if both servers are started
- check if lsp-mode is still enabled in this buffer (this happened to me before, it turns of somehow after I revert the buffer)

**Comment by RobinBeekhof** [comment]
![image](https://user-images.githubusercontent.com/50193227/141175045-00f5716e-789e-427c-9d72-d9e12d07fb7d.png)

This is what I get when running M-x lsp-describe-session. I guess red means it is off? How can I restart it?

**Comment by merrickluo** [comment]
Red is fine, it looks normal to me. does html-ls work?

**Comment by RobinBeekhof** [comment]
Yes, it's strange... HTML-ls seems to work fine

![image](https://user-images.githubusercontent.com/50193227/142154916-c0b0f99e-0e9b-48bd-87e5-c97330ca0ad5.png)

**Comment by merrickluo** [comment]
it might be a project-specific problem then,  can you try `lsp-toggle-trace-io` and then `lsp-workspace-show-log` to see if any error is reported by the tailwindcss server?

**Comment by RobinBeekhof** [comment]
yes that worked! With `lsp-toggle-trace-io` and then `lsp-workspace-show-log` I found a mistake in my project setup... Now It works like a charm!  Thanks! I will close this issue
