### ISSUE TITLE
Package runs into an error when opening a file using web-mode

### ISSUE THREAD

**Issue by nicolasferraro** [merrickluo/lsp-tailwindcss#49]
I'm running into a weird issue when opening a `.html.erb` file using web-mode. I've verified that the server is installed and I also can confirm it works when opening a plain `.html` file. 

Any clues of what may be causing this? Ah btw, I'm using doom on emacs 28

<img width="1461" alt="Screen Shot 2022-11-01 at 16 40 02" src="https://user-images.githubusercontent.com/19378450/199324414-69e1e955-4b42-4d65-9dd8-421a94152144.png">

Here's the package's config, an exact copy from what the README suggests
```elisp
(use-package lsp-tailwindcss
  :init
  (setq lsp-tailwindcss-add-on-mode t))
```

**Comment by merrickluo** [comment]
erb works fine for me, I remember there was an old bug in `lsp-mode` has the same error message when running with add-on mode.
I'm not sure you're on which commit of doom, can you try adding `(unpin! lsp-mode)` to `packages.el` and sync?

**Comment by nicolasferraro** [comment]
> I'm not sure you're on which commit of doom, can you try adding (unpin! lsp-mode) to packages.el and sync?

I tried that and also upgrading doom but I still see the issue (I'm now in the latest doom)

>erb works fine for me, I remember there was an old bug in lsp-mode has the same error message when running with add-on mode.

A google search returns a few results for this, thank you for pointing me in the right direction! I'll keep playing around with it until I find out what it is. I'll be closing this since it doesn't seem to be an issue with your package :)
