### ISSUE TITLE
Seems to cause ts-ls to not be activated in the same .tsx file by default

### ISSUE THREAD

**Issue by x-ji** [merrickluo/lsp-tailwindcss#58]
Not sure if it has always been like this, but I just realized that when I open a `.tsx` file, only the tailwind lsp is activated for some reason, even though `ts-ls` is also installed. After I uninstalled `lsp-tailwindcss` (couldn't figure out what config to tweak otherwise), `ts-ls` is activated as expected. I thought from https://github.com/emacs-lsp/lsp-mode/issues/424 that having multiple lsps run on the same buffer is supported, but maybe I'm wrong though. Or maybe I'm configuring something incorrectly here.

**Comment by cmetz** [comment]
did you set the lsp-tailwindcss-add-on-mode as described in the README

**Comment by x-ji** [comment]
@cmetz Thanks for the pointer. You're right and this works. Apparently I didn't read the README carefully enough. Sorry 🙈
