### ISSUE TITLE
Is spacemacs integration supported? If so how 

### ISSUE THREAD

**Issue by sukidhar** [merrickluo/lsp-tailwindcss#60]
I am a newbie to emacs and spacemacs. I find it amusing to use spacemacs however I couldn’t get tailwind css intellisense working in spacemacs, if there’s any steps or procedure to follow. it would be great to work

**Comment by sukidhar** [comment]
> I am a newbie to emacs and spacemacs. I find it amusing to use spacemacs however I couldn’t get tailwind css intellisense working in spacemacs, if there’s any steps or procedure to follow. it would be great to work

Never mind, got it working

**Comment by wilsonwg** [comment]
@sukidhar 

Do you mind to share the steps of setting up the integration? I need it for Spacemacs.
