### ISSUE TITLE
lsp-log is too verbose

### ISSUE THREAD

**Issue by yenda** [merrickluo/lsp-tailwindcss#64]
At first I thought that things were not working because I couldn't get any completion, but I realized I was getting some in the few seconds after restarting the server. The logs are growing from 0 to 100MB in under a minute, and from there, it gets so slow that the completions aren't showing up anymore.

Everything works great after setting lsp-log to nil but it would be great if there was a way to make lsp-tailwindcss logs less verbose. For instance clojure-lsp in the meantime only logged about 1MB

**Comment by artemkovalyov** [comment]
I think it depends on what the server returns. And for the completion it returns A LOT in case of Tailwind.
Working with lsp-log enabled is like a conscious suicide, it's not recommended and one of the key performance improvements recommendation for `lsp-mode` to keep it off.
It's slow anyways...

**Comment by artemkovalyov** [comment]
Try `lsp-bridge` - it flies! They failed to figure out Tailwind though and created a custom backend for it which of course wouldn't consider your custom config compared to LSP. 
I tried to fix it but failed for now: https://github.com/manateelazycat/lsp-bridge/issues/882

**Comment by merrickluo** [comment]
yes as @artemkovalyov mentioned the lsp-log logs all the requests/responses between the client and server, so there is not something we can control here, it is only recommended to turn on the log when trying to debug issues, you should not need it when using it.
