### ISSUE TITLE
add-on mode is not working properly

### ISSUE THREAD

**Issue by merrickluo** [merrickluo/lsp-tailwindcss#7]
see #1

**Comment by XMasterNinni** [comment]
I've updated both gccmacs and doom and ts-ls + tailwindcss are now starting concurrently in rjsx-mode. Seems like my issue wasn't related to this client at all! 

`(use-package! lsp-tailwindcss
  :init (setq! lsp-tailwindcss-add-on-mode t))
`

Everything seems to work as expected and as far as i can tell, suggestions only occur when inside the className quotation marks :100:

**Comment by merrickluo** [comment]
that's great, I'm still seeing error messages when ts-ls and tailwindcss both running though..

**Comment by merrickluo** [comment]
the hover issue seems to be fixed by https://github.com/emacs-lsp/lsp-mode/pull/2654, closing
