### ISSUE TITLE
How do I configure lsp-tailwindcss to show hover previews in a childframe instead of the minibuffer?

### ISSUE THREAD

**Issue by KJSanchez** [merrickluo/lsp-tailwindcss#77]
# Observed Behavior
css preview is shown in the minibuffer when hovering
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/d7c04ad6-d9d9-4253-a274-c645986bae3b">

# Desired Behavior
CSS preview is shown in a childframe. I'm able to get this behavior with `M-x lsp-ui-doc-glance`

<img width="826" alt="image" src="https://github.com/user-attachments/assets/925b4458-d31a-448d-9cdb-23683feaf093">

**Comment by merrickluo** [comment]
Hi @KJSanchez, this is not controlled by lsp-tailwindcss, it merely provide the connection and some hack to make it work, I rmb lsp-ui used to provide a customization for this, but seems to be removed, maybe you can try https://github.com/casouri/eldoc-box?

I'll close this as there is not much I can do, thanks.
