### ISSUE TITLE
Setting up language service

### ISSUE THREAD

**Issue by wojtekgalaj** [merrickluo/lsp-tailwindcss#8]
Hi,

First of all, thanks a million for sharing this work. This is the only thing from vscode I was wishing to have :)

I'm having trouble getting this to work however. I think what I don't understand is how to set up the language service. 

Following your readme I found the vscode plugin. I also found ```tailwindcss-language-service@0.0.12``` on npm. 

I tried cloning the former into ```~/.emacs.d/.local/etc/lsp ``` and installing the latter with ```npm i -g```, then using the settings your program provides to point it to service's ```index.js```, but I don't see completions for tailwind classes.

It might be worth mentioning I'm running ```svelte-language-server@0.10.101``` on that project.

My question is, how should I install the language service properly.

Thanks

**Comment by merrickluo** [comment]
you can install it with `M-x lsp-install-server` and select `tailwindcss`, you should also set `lsp-tailwindcss-add-on-mode` to `t` in the init block of use-package (or set it before requiring lsp-tailwindcss) if you want it to run with another language server. but multiple language server might not working well together, see #1

**Comment by wojtekgalaj** [comment]
Thanks, I found the meta command for this. I installed the server and set add on mode.

I still don't see the completions but I understand this is not enough information for you to be able to help.

I'm sure it's something borked in my config. I'll figure it out.

**Comment by merrickluo** [comment]
do you have a `tailwind.config.js` file in the project? It only starts lsp-tailwindcss if the config file exists in the project root, I've updated the master to also detect it when it's not in the project root.

**Comment by wojtekgalaj** [comment]
I do have tailwind config in the root of the project. I think I have more trouble in my config. Go to definition is now hanging without any errors and I need to C-g out of it to unblock the ui so I need to sort these things before I can keep debugging this plugin. I'm on doom emacs and that keep changing almost daily, I might need to give setting emacs up from scratch a go as I often feel lost with what's happening with doom.

I'll close this issue for now and open up another one if I have more details and a reproduction for my problem.
